### PR TITLE
First Assignment Rikesh

### PR DESCRIPTION
**Pull request by rikeshkarki**

### CODE REVIEW

**Comment by kxhitiz** [comment]
@kxhitiz are you sure you wanna close this pr?

**Comment by kxhitiz** [comment]
@rikeshkarki are you sure you wanna close this pr?

**Comment by kxhitiz** [comment]
aba github ma chat garnu parla jasto chha, lol

**Comment by rikeshkarki** [comment]
Ahh, haha. What's up?

**Comment by kxhitiz** [comment]
missing the fried chicken i had there

**Comment by rikeshkarki** [comment]
Aww. Should ve packed a suitcase full of it n taken with you.

**Comment by bhanubhakta** [comment]
@rikeshkarki what's up? Why closing this? Seems like something is going on. 😸

**Pull request closed without merging**
